# Workshop 8 [Student]

This notebook will cover the following topics:

1. Numpy Array
2. Attributes and Operations
3. Reading data from CSV
4. Statistics
5. Indexing
6. Copy vs View
7. Modifications

## 8.1 NUMPY ARRAY (Follow)

**Learning Objectives:**

1. Understand the numpy module.
2. Understand numpy arrays.
3. Understand Array creation and basic functions.
4. Learn to manipulate arrays

In [ ]:
#https://numpy.org/doc/stable/reference/arrays.dtypes.html
"""
Add comments for you own reference
"""

import numpy as np
x = np.array([[1,2,3,4,5],
                 [6,7,8,9,0],
                 [5,4,3,2,1]])
print(x)
print("Type -",type(x))
print("Data Type -",x.dtype)
print("Size -",x.size)
print("ItemSize -",x.itemsize)
print("Dimensions -",x.ndim)
print("Shape -",x.shape)

In [ ]:
"""
Add comments for you own reference
"""

import numpy as np
x = np.full(5,3)
print("Full:\n",x)
x = np.zeros((2,4))
print("Zeros:\n",x)
x = np.ones((2,5))
print("Ones:\n",x)
x = np.arange(1,7)
print("Range:\n",x)
x = np.linspace(1,5,6)
print("LinSpace:\n",x)

In [ ]:
"""
Add comments for you own reference
"""

import numpy as np
x = np.arange(1,10)
print("Array X:\n",x,"\n")
print("Multiplication:\n",x*2,"\n")
print("Substraction:\n",x-2,"\n")
y = np.arange(3,12)
print("Array Y:\n",y,"\n")
print("SHAPES -",x.shape,y.shape,"\n")
print("Addition:\n",x+y,"\n")
print("Multiplication:\n",x*y,"\n")

**Evaluation:**

After running this program, think about and answer these questions:

1. What does the arange function do? creates a Numpy array
2. What is the use of 1s and 0s function? Create a numpy array with either 0's or 1's
3. What will happen if shapes of arrays are not same? ValueError: operands could not be broadcast together with shapes (8,) (9,) 
4. Try to add more dimentions to the arrays.

## 8.1 NUMPY ARRAY (Group)

Write a program that will do the following:

1. Create 3 Arrays:
    - X : containing Multiples of 5
    - Y : in range of 100 to 150
    - Z : containg all n (taken from user) 
2. Make sure that Shapes of arrays are equal.
3. Perform:
    - X + Y
    - X * Z
    - Z - Y
    - X + Y + Z

In [ ]:
import numpy as np

class NumpyArray:
    def __init__(self,*z):
        self.z = np.array(z)
        self.x = np.arange(5,5*len(self.z)+1,5)
        self.y = np.random.randint(100,150,(len(self.z)))   
        
    
    def AddXY(self):
        print( self.x + self.y)

    def MultiplyXZ(self):
        print (self.x * self.z)

    def SubtractZY(self):
        print (self.z-self.y)

    def addXYZ(self):
        print (self.x + self.y + self.z)

    def getShapes(self):
        print (f'The shape of X is {np.shape(self.x)}. The shape of Y is {np.shape(self.y)}. The shape of Z is {np.shape(self.z)}')
     


In [ ]:

myArray = NumpyArray(1,3,5,6)
print(myArray.x)
print(myArray.z)
print(myArray.y)
myArray.getShapes()
myArray.AddXY()
myArray.MultiplyXZ()
myArray.SubtractZY()
myArray.addXYZ()


## 8.2 READING CSV (Follow)

**Learning Objectives:**

1. Understand how to read CSV into arrays.
2. Understand the data type of csv files.
3. Learn to manipulate CSV data.

In [ ]:
"""
Add comments for you own reference
"""

import numpy as np

data = np.loadtxt("test.csv",delimiter=",", dtype=int)
print(data)

In [ ]:
"""
Add comments for you own reference
"""

print("Type -",type(data))
print("Data Type -",data.dtype)
print("Size -",data.size)
print("ItemSize -",data.itemsize)
print("Dimensions -",data.ndim)
print("Shape -",data.shape)

**Evaluation:**

After running this program, think about and answer these questions:

1. What does astype() function do?
2. Search for alternate methods of loading.
3. What is the use of delimiter parameter?

## 8.2 READING CSV (Group)

Write a program that will do the following:

1. Read csv file 'test.csv'
2. Perform basic operations on 'test.csv'
    - Multiply each value by 2
    - Subtract each value by 50
3. Create an array X with same shape and random numbers
4. Add X to data
   

In [ ]:
import numpy as np

class reading_CSV:
    def __init__(self,Filename):
        self.__filename = Filename
        self.__data = np.loadtxt(self.__filename,delimiter=",", dtype=int)
        self.__x =None
        
    def csvX2(self):
        self.__twos = np.full(self.__data.shape,2)
        print(self.__twos*self.__data)

    def csvMinus50(self):
        self.__fiftys = np.full(self.__data.shape,50)
        print(self.__data-self.__fiftys)

    def rndmX(self):
        self.__x = np.random.randint(1,99,self.__data.shape)
        print(self.__x)

    def AppendX(self):
        self.rndmX()
        print(self.__x.shape)
        newArr = np.concatenate((self.__data,self.__x),axis=0, out=None, dtype=int, casting="same_kind")
        print(newArr.shape)
        np.savetxt('appendCSV.csv',newArr,delimiter=",")

    def __str__(self):
        return f'{self.__data.shape}'

In [ ]:
myCSV = reading_CSV('test.csv')
#myCSV.csvX2()
#myCSV.csvMinus50()

myCSV.AppendX()

## 8.3 STATISTICS (Follow)

**Learning Objectives:**

1. Learn to perform statistical functions on Arrays.
2. Understand how arrays provide statistical analysis.
3. Understand how to perform statistical analysis of different dimensions of an array.

In [ ]:
"""
Add comments for you own reference
"""

import numpy as np

data = np.loadtxt("test.csv",delimiter=",", dtype=int)

print("Mean -")
print(data.mean())
print("Median -")
print(np.median(data))
print("Sum -")
print(np.sum(data[0]))
print("Standard Deviation -")
print(np.std(data))
print("Variation -")
print(np.var(data))

In [ ]:
#https://railsware.com/blog/python-for-machine-learning-pandas-axis-explained/#:~:text=%E2%80%9Caxis%200%E2%80%9D%20represents%20rows%20and,it%20goes%20along%20rows%20direction.
"""
Add comments for you own reference
"""

print("Mean by Rows-")
print(data.mean(axis=0))
print("Mean by Column-")
print(data.mean(axis=1))

**Evaluation:**

After running this program, think about and answer these questions:

1. What other functions are readily available?
2. What does axis parameter do?
3. How will different functions react to changes in dimensions of the array?

## 8.3 STATISTICS (Group)

Write a program that will do the following:

1. Get a number n from User (10-30)
2. Print the statistic information for every nth row of the 'test.csv'
    - Mean
    - Median
    - Sum
    - SD
    - Variation


In [ ]:
import numpy as np

class reading_CSV:
    def __init__(self,Filename):
        self.__filename = Filename
        self.__data = np.loadtxt(self.__filename,delimiter=",", dtype=int)
        self.__x =None

    def PullNthRow(self):
        N = int(input('Please enter a number between 1 and 30'))
        I = N
        while (I <= self.__data.shape[0]):
            print(f'for row {I}: {self.__data[I]}\nMean - {self.__data[I].mean()}, Median - {np.median(self.__data[I])}, Sum - {np.sum(self.__data[I])}, Standard Dev - {np.std(self.__data[I])}, Variation - {np.var(self.__data[I])}')
            I += N
    
    def __str__(self):
        return f'{self.__data.shape}'


In [ ]:
myCSV = reading_CSV('test.csv')
myCSV.PullNthRow()

## 8.4 INDEXING (Follow)

**Learning Objectives:**

1. Understand how Indexing in arrays works.
2. Understand how slicing in arrays works.
3. Learn to extract relevant information from numpy array.

In [29]:
"""
Add comments for you own reference
"""

import numpy as np

data = np.loadtxt("test.csv",delimiter=",", dtype=int)
print(data[20])
print('Item at index (20,4):\n',data[20,4],'\n')

[66 97  7 18 39 84  4 26 21 81]
Item at index (20,4):
 39 



In [30]:
"""
Add comments for you own reference
"""

print('Slice of rows 20 - 25:\n',data[20:25],'\n')
print('Specific rows (multiples of 10):\n',data[[i for i in range(0,100,10)]],'\n')

Slice of rows 20 - 25:
 [[66 97  7 18 39 84  4 26 21 81]
 [20 66 56 59 66 53  2 64 73 12]
 [89  8 26 29 49 82 39 22 31 33]
 [49 76 11 30 28 21 18 57 95 69]
 [92 81 85 26 21  7 58 48 47 56]] 

Specific rows (multiples of 10):
 [[53 28 85 13 57 72 46 31 73 32]
 [40  9 25 88 61 86 93 77 74 73]
 [66 97  7 18 39 84  4 26 21 81]
 [86 18 80 32 77 54  2 17 75 35]
 [42  8 78 74 99  5  3  3 48 13]
 [45 99 25 94 38 80 22 15 59 67]
 [17  8 24 88 35 17 45 62  2 15]
 [26 69  9 85 20 51 66  7 81 10]
 [97 90 69 73 28 13 68 41 12 64]
 [59 70 25 94 67  2 87 65 53 62]] 



In [36]:
"""
Add comments for you own reference
"""

print('Slice of columns 5 - 8:\n',data[2:6:,5:8],'\n')
print('Specific columns (multiples of 2):\n',data[:,[i for i in range(0,10,2)]],'\n')

Slice of columns 5 - 8:
 [[97 76 21]
 [55 63 42]
 [93 41 75]
 [74 11  7]] 

Specific columns (multiples of 2):
 [[53 85 57 46 73]
 [50 87 82 86  2]
 [74 77 69 76 75]
 [61  7  6 63 77]
 [58 77 68 41 77]
 [59 52 12 11 84]
 [12 46 85 73 31]
 [77 56 21 30 83]
 [24 21 72 16 51]
 [63 95 69 81 92]
 [40 25 61 93 74]
 [81 13 41 50 90]
 [87 73 10 21 68]
 [33 82 92 83 58]
 [61 64 19 44 78]
 [51 46 13 48 19]
 [33 58 41 22 40]
 [37 10 89 12  1]
 [96 80  6 34 80]
 [67 93 73 47 73]
 [66  7 39  4 21]
 [20 56 66  2 73]
 [89 26 49 39 31]
 [49 11 28 18 95]
 [92 85 21 58 47]
 [37 41 59 85 68]
 [26 31 23 18 67]
 [83 30 92 76 33]
 [69 46 42 67 26]
 [83 82 30 34 64]
 [86 80 77  2 75]
 [56 47 23 66 15]
 [10 79 79  6 16]
 [31 35 54 92  1]
 [21 18 46 16 61]
 [59 29 40 10 42]
 [10 53 63 32 83]
 [85 59 62 91 74]
 [75 87 31 51 51]
 [93  5 14 17 26]
 [42 78 99  3 48]
 [61 30 27 62 87]
 [55 43 17 77 92]
 [11 85 62 75 17]
 [10 91 81  1 59]
 [69  3 38 60 21]
 [95 88 50  2 59]
 [76 58 22 22 63]
 [21 76 35 36 11]
 [80 5

In [ ]:
"""
Add comments for you own reference
"""

print('Slice of rows 20-25 & columns 5 - 8:\n',data[20:25,5:8],'\n')

**Evaluation:**

After running this program, think about and answer these questions:

1. What is the use case for slicing and indexing?
2. Try to manipulate the array by slicing differently.

## 8.4 INDEXING (Group)

Write a program that will do the following:

1. Use 'test.csv' 
2. Get a row and column number from the user and display the value at the index
3. Get a range of rows and columns from the user and display all rows in column range and all columns in row range and also all data in row and column range
4. Add rows 10-15 with rows 50-55 and display output

In [66]:
import numpy as np

class reading_CSV:
    def __init__(self,Filename):
        self.__filename = Filename
        self.__data = np.loadtxt(self.__filename,delimiter=",", dtype=int)  

    #Get a row and column number from the user and display the value at the index
    def Indexing_1(self,x,y): 
        print(f'Item at index {x},{y}:\n',self.__data[x,y],'\n')

    #Get a range of rows and columns from the user and display all rows 
    def Indexing_2(self,x,y): 
        print(f'Item range [{x}:{y}]:\n',self.__data[x:y],'\n')
    
    #Get a range of rows and columns from the user and display all rows in column range and all columns in row range and also all data in row and column range
    def Indexing_3(self,x1,x2,y1,y2): 
        self.Indexing_2(x1,x2)
        print(f'Slice of rows {x1}-{x2} amd columns {y1}-{y2}:\n',data[x1:x2:,y1:y2],'\n')    

    def Indexing_4(self): 
        print(self.__data[10:16])
        print(self.__data[50:56])
        print(self.__data[10:16]+self.__data[50:56])
        

In [67]:
myCSV = reading_CSV('test.csv')
myCSV.Indexing_4()


[[40  9 25 88 61 86 93 77 74 73]
 [81 58 13 30 41 41 50 44 90  1]
 [87 37 73 14 10 11 21 84 68 22]
 [33  6 82 37 92 32 83  1 58 79]
 [61 53 64 77 19 56 44 31 78 93]
 [51 34 46 54 13 72 48 65 19 83]]
[[45 99 25 94 38 80 22 15 59 67]
 [22 43 29 21 47 69 24 76 59 23]
 [45 91 88 49 15 61 16 68 66  4]
 [34 14 15 78 22 55 23 68 39 40]
 [62 71 33 69 65 66 46 24 80 87]
 [13 61 84 52 12 74  7 86 19  7]]
[[ 85 108  50 182  99 166 115  92 133 140]
 [103 101  42  51  88 110  74 120 149  24]
 [132 128 161  63  25  72  37 152 134  26]
 [ 67  20  97 115 114  87 106  69  97 119]
 [123 124  97 146  84 122  90  55 158 180]
 [ 64  95 130 106  25 146  55 151  38  90]]


In [43]:
myCSV.Indexing_2(5,10)


Item range [5:10]:
 [[59 55 52 63 12 74 11  7 84 40]
 [12 11 46 30 85 46 73 79 31 35]
 [77 20 56 32 21 83 30 32 83 24]
 [24 80 21 79 72 18 16 44 51 61]
 [63 64 95 29 69 52 81 64 92 65]] 



In [44]:
myCSV.Indexing_3(5,10,3,5)


Item range [5:10]:
 [[59 55 52 63 12 74 11  7 84 40]
 [12 11 46 30 85 46 73 79 31 35]
 [77 20 56 32 21 83 30 32 83 24]
 [24 80 21 79 72 18 16 44 51 61]
 [63 64 95 29 69 52 81 64 92 65]] 

Slice of rows 5-10 amd columns 3-5:
 [[63 12]
 [30 85]
 [32 21]
 [79 72]
 [29 69]] 



## 8.5 COPY VS VIEW (Follow)

**Learning Objectives:**

1. Understand the difference between a copy and a view.
2. Understand how the original array is affected when deling with views.
3. Understand how the original array is affected when deling with copies.
4. Learn to manipulate data using copies and views

In [4]:
"""
Add comments for you own reference
"""
import numpy as np
arr = np.array([1,2,3,4,5])
print("Original Before -")
print(arr)
x = arr.view()
x[0] = 9
print("Original for view -")
print(arr)
print("View -")
print(x)
y = arr.copy()
y[1] = 8
print("Original for copy -")
print(arr)
print("Copy -")
print(y)

Original Before -
[1 2 3 4 5]
Original for view -
[9 2 3 4 5]
View -
[9 2 3 4 5]
Original for copy -
[9 2 3 4 5]
Copy -
[9 8 3 4 5]


In [10]:
"""
Add comments for you own reference
"""

data = np.loadtxt("test.csv",delimiter=",", dtype=int)
data = data[5:10]

print("Original Before -")
print(data)
x = data.view()
x[0::2] = 10
print("Original for view -")
print(data)
print("View -")
print(x)
y = data.copy()
y[1::2] = 8
print("Original for copy -")
print(data)
print("Copy -")
print(y)

Original Before -
[[59 55 52 63 12 74 11  7 84 40]
 [12 11 46 30 85 46 73 79 31 35]
 [77 20 56 32 21 83 30 32 83 24]
 [24 80 21 79 72 18 16 44 51 61]
 [63 64 95 29 69 52 81 64 92 65]]
Original for view -
[[10 10 10 10 10 10 10 10 10 10]
 [12 11 46 30 85 46 73 79 31 35]
 [10 10 10 10 10 10 10 10 10 10]
 [24 80 21 79 72 18 16 44 51 61]
 [10 10 10 10 10 10 10 10 10 10]]
View -
[[10 10 10 10 10 10 10 10 10 10]
 [12 11 46 30 85 46 73 79 31 35]
 [10 10 10 10 10 10 10 10 10 10]
 [24 80 21 79 72 18 16 44 51 61]
 [10 10 10 10 10 10 10 10 10 10]]
Original for copy -
[[10 10 10 10 10 10 10 10 10 10]
 [12 11 46 30 85 46 73 79 31 35]
 [10 10 10 10 10 10 10 10 10 10]
 [24 80 21 79 72 18 16 44 51 61]
 [10 10 10 10 10 10 10 10 10 10]]
Copy -
[[10 10 10 10 10 10 10 10 10 10]
 [ 8  8  8  8  8  8  8  8  8  8]
 [10 10 10 10 10 10 10 10 10 10]
 [ 8  8  8  8  8  8  8  8  8  8]
 [10 10 10 10 10 10 10 10 10 10]]


**Evaluation:**

After running this program, think about and answer these questions:

1. What does the copy() function do?
2. What does the view() function do?
3. How is the original array affected by manipulating views / copies?
4. What is the best use case for views?
5. What is the best use case for copies?

## 8.5 COPY VS VIEW (Group)

Write a program that will do the following:

1. Read 'test.csv' 
2. Make a copy and a view of the data
3. Convert even rows of view to all 5
4. Convert odd rows of copy to all 10
5. Add Copy to view
6. Display all three Arrays

In [26]:
import numpy as np

class reading_CSV:
    def __init__(self,Filename):
        self.__filename = Filename
        self.__data = np.loadtxt(self.__filename,delimiter=",", dtype=int)
        self.__datacp = None
        self.__datavw = None

    def getData(self):
        print(self.__data[0:5])

    def Copydata(self):
        self.__datacp = self.__data[0:5].copy()
        self.__datacp[0::2] = 10
        print (self.__datacp)

    def ViewData(self):
        self.__datavw = self.__data[0:5].view()
        self.__datavw[1::2] = 5
        print (self.__datavw)

    def CopyView(self):
        copyView = self.__datavw.copy()
        print(copyView.base)
        print(copyView)
        #print(f'the Base of the origonal array is: {self.__data.base}\nThe Base of the view is: {self.__datavw.base}\n The Base of the copy is: {self.__datacp.base}')


    #Get a row and column number from the user and display the value at the index
    def Indexing_1(self,x,y): 
        print(f'Item at index {x},{y}:\n',self.__data[x,y],'\n')

    #Get a range of rows and columns from the user and display all rows 
    def Indexing_2(self,x,y): 
        print(f'Item range [{x}:{y}]:\n',self.__data[x:y],'\n')
    
    #Get a range of rows and columns from the user and display all rows in column range and all columns in row range and also all data in row and column range
    def Indexing_3(self,x1,x2,y1,y2): 
        self.Indexing_2(x1,x2)
        print(f'Slice of rows {x1}-{x2} amd columns {y1}-{y2}:\n',data[x1:x2:,y1:y2],'\n')    

    def Indexing_4(self): 
        print(self.__data[10:16])
        print(self.__data[50:56])
        print(self.__data[10:16]+self.__data[50:56])


In [27]:
mynumpy = reading_CSV('test.csv')
mynumpy.getData()
mynumpy.Copydata()
mynumpy.ViewData()

[[53 28 85 13 57 72 46 31 73 32]
 [50 90 87 98 82 35 86 30  2 43]
 [74 53 77  1 69 97 76 21 75  3]
 [61 67  7 21  6 55 63 42 77  6]
 [58 82 77  7 68 93 41 75 77 19]]
[[10 10 10 10 10 10 10 10 10 10]
 [50 90 87 98 82 35 86 30  2 43]
 [10 10 10 10 10 10 10 10 10 10]
 [61 67  7 21  6 55 63 42 77  6]
 [10 10 10 10 10 10 10 10 10 10]]
[[53 28 85 13 57 72 46 31 73 32]
 [ 5  5  5  5  5  5  5  5  5  5]
 [74 53 77  1 69 97 76 21 75  3]
 [ 5  5  5  5  5  5  5  5  5  5]
 [58 82 77  7 68 93 41 75 77 19]]


## 8.6 MODIFICATION (Follow)

**Learning Objectives:**

1. Understand how to modify an array.
2. Learn modification functions.
3. Understand the use of array modification

In [28]:
"""
Add comments for you own reference
"""

import numpy as np
arr = np.array([1,2,3,4,5,6])
arr.resize(2,3)
print(arr,"\n")
x = arr.reshape(3,2)
print(x,"\n")
y = x.flatten()
z = x.ravel()
y[0] = 99
z[0] = 88
print(x,"\n")
print(y,"\n")
print(z,"\n")
print(x.transpose(),"\n")

[[1 2 3]
 [4 5 6]] 

[[1 2]
 [3 4]
 [5 6]] 

[[88  2]
 [ 3  4]
 [ 5  6]] 

[99  2  3  4  5  6] 

[88  2  3  4  5  6] 

[[88  3  5]
 [ 2  4  6]] 



In [29]:
"""
Add comments for you own reference
"""

data = np.loadtxt("test.csv",delimiter=",", dtype=str).astype(int)
data = data[25:30]

data.resize(25,2)
print(data,"\n")
x = data.reshape(10,5)
print(x,"\n")
y = x.flatten()
z = x.ravel()
y[0] = 99
z[0] = 88
print(x,"\n")
print(y,"\n")
print(z,"\n")
print(x.transpose(),"\n")

[[37 80]
 [41 91]
 [59 28]
 [85  6]
 [68 74]
 [26 90]
 [31 28]
 [23 45]
 [18 23]
 [67 53]
 [83 17]
 [30 50]
 [92 23]
 [76  7]
 [33 67]
 [69 20]
 [46 89]
 [42 30]
 [67 36]
 [26 49]
 [83 61]
 [82  6]
 [30 22]
 [34 75]
 [64 78]] 

[[37 80 41 91 59]
 [28 85  6 68 74]
 [26 90 31 28 23]
 [45 18 23 67 53]
 [83 17 30 50 92]
 [23 76  7 33 67]
 [69 20 46 89 42]
 [30 67 36 26 49]
 [83 61 82  6 30]
 [22 34 75 64 78]] 

[[88 80 41 91 59]
 [28 85  6 68 74]
 [26 90 31 28 23]
 [45 18 23 67 53]
 [83 17 30 50 92]
 [23 76  7 33 67]
 [69 20 46 89 42]
 [30 67 36 26 49]
 [83 61 82  6 30]
 [22 34 75 64 78]] 

[99 80 41 91 59 28 85  6 68 74 26 90 31 28 23 45 18 23 67 53 83 17 30 50
 92 23 76  7 33 67 69 20 46 89 42 30 67 36 26 49 83 61 82  6 30 22 34 75
 64 78] 

[88 80 41 91 59 28 85  6 68 74 26 90 31 28 23 45 18 23 67 53 83 17 30 50
 92 23 76  7 33 67 69 20 46 89 42 30 67 36 26 49 83 61 82  6 30 22 34 75
 64 78] 

[[88 28 26 45 83 23 69 30 83 22]
 [80 85 90 18 17 76 20 67 61 34]
 [41  6 31 23 30  7 46 36 82

**Evaluation:**

After running this program, think about and answer these questions:

1. What is the difference between resize and reshape?
2. What is the difference between ravel and flatten?
3. What does transpose() function do?
4. How are these functions helpful in data analysis or statistics?

## 8.6 MODIFICATION (Group)

Write a program that will do the following:

1. Read 'test.csv' 
2. Slice a 5:8 grid from the array (X)
3. Make a copy and transpose (X)
4. Reshape both arrays to (4,10)
5. Multiply the arrays and display the Output
6. Try to display each step

In [50]:
import numpy as np

class reading_CSV:
    def __init__(self,Filename):
        self.__filename = Filename
        self.__data = np.loadtxt(self.__filename,delimiter=",", dtype=int)
        self.__datacp = None
        self.__datavw = None

    #Get a range of rows and columns from the user and display all rows 
    def Slice5X8(self): 
        print('Read in Test.csv and slice a 5X8 portion of it. name the slice x.\nx = self.__data[:5:, :8].copy() ')
        x = self.__data[:5:, :8].copy()
        print(x)
        print('X into y and reshape y to 4X10\ny = x.reshape(4,10)')
        y = x.transpose()
        y = y.reshape(4,10)
        print(y)
        print('Reshape x to 4X10') 
        x.reshape(4,10)
        print(x)
        print('Multiply x and y:')
        print(x.reshape(4,10)*y)

    def Copydata(self):
        self.__datacp = self.__data[:20:2].copy()
        print (self.__datacp)
    
    #Get a range of rows and columns from the user and display all rows in column range and all columns in row range and also all data in row and column range
    def Indexing_3(self,x1,x2,y1,y2): 
        self.Indexing_2(x1,x2)
        print(f'Slice of rows {x1}-{x2} amd columns {y1}-{y2}:\n',data[x1:x2:,y1:y2],'\n')    

    def Indexing_4(self): 
        print(self.__data[10:16])
        print(self.__data[50:56])
        print(self.__data[10:16]+self.__data[50:56])



In [51]:
mynumpy = reading_CSV('test.csv')
mynumpy.Slice5X8()


Read in Test.csv and slice a 5X8 portion of it. name the slice x.
x = self.__data[:5:, :8].copy() 
[[53 28 85 13 57 72 46 31]
 [50 90 87 98 82 35 86 30]
 [74 53 77  1 69 97 76 21]
 [61 67  7 21  6 55 63 42]
 [58 82 77  7 68 93 41 75]]
X into y and reshape y to 4X10
y = x.reshape(4,10)
[[53 50 74 61 58 28 90 53 67 82]
 [85 87 77  7 77 13 98  1 21  7]
 [57 82 69  6 68 72 35 97 55 93]
 [46 86 76 63 41 31 30 21 42 75]]
Reshape x to 4X10
[[53 28 85 13 57 72 46 31]
 [50 90 87 98 82 35 86 30]
 [74 53 77  1 69 97 76 21]
 [61 67  7 21  6 55 63 42]
 [58 82 77  7 68 93 41 75]]
Multiply x and y:
[[2809 1400 6290  793 3306 2016 4140 1643 3350 7380]
 [7395 8526 6314  245 6622  390 7252   53 1617    7]
 [3933 7954 5244  126 4148 4824  245 2037  330 5115]
 [2898 3612 4408 5166 3157  217 2040 1953 1722 5625]]
