# Workshop 8 [Student]

This notebook will cover the following topics:

1. Numpy Array
2. Attributes and Operations
3. Reading data from CSV
4. Statistics
5. Indexing
6. Copy vs View
7. Modifications

## 8.1 NUMPY ARRAY (Follow)

**Learning Objectives:**

1. Understand the numpy module.
2. Understand numpy arrays.
3. Understand Array creation and basic functions.
4. Learn to manipulate arrays

In [ ]:
#https://numpy.org/doc/stable/reference/arrays.dtypes.html
"""
Add comments for you own reference
"""

import numpy as np
x = np.array([[1,2,3,4,5],
                 [6,7,8,9,0],
                 [5,4,3,2,1]])
print(x)
print("Type -",type(x))
print("Data Type -",x.dtype)
print("Size -",x.size)
print("ItemSize -",x.itemsize)
print("Dimensions -",x.ndim)
print("Shape -",x.shape)

In [ ]:
"""
Add comments for you own reference
"""

import numpy as np
x = np.full(5,3)
print("Full:\n",x)
x = np.zeros((2,4))
print("Zeros:\n",x)
x = np.ones((2,5))
print("Ones:\n",x)
x = np.arange(1,7)
print("Range:\n",x)
x = np.linspace(1,5,6)
print("LinSpace:\n",x)

In [ ]:
"""
Add comments for you own reference
"""

import numpy as np
x = np.arange(1,10)
print("Array X:\n",x,"\n")
print("Multiplication:\n",x*2,"\n")
print("Substraction:\n",x-2,"\n")
y = np.arange(3,12)
print("Array Y:\n",y,"\n")
print("SHAPES -",x.shape,y.shape,"\n")
print("Addition:\n",x+y,"\n")
print("Multiplication:\n",x*y,"\n")

**Evaluation:**

After running this program, think about and answer these questions:

1. What does the arange function do? creates a Numpy array
2. What is the use of 1s and 0s function? Create a numpy array with either 0's or 1's
3. What will happen if shapes of arrays are not same? ValueError: operands could not be broadcast together with shapes (8,) (9,) 
4. Try to add more dimentions to the arrays.

## 8.1 NUMPY ARRAY (Group)

Write a program that will do the following:

1. Create 3 Arrays:
    - X : containing Multiples of 5
    - Y : in range of 100 to 150
    - Z : containg all n (taken from user) 
2. Make sure that Shapes of arrays are equal.
3. Perform:
    - X + Y
    - X * Z
    - Z - Y
    - X + Y + Z

In [ ]:
import numpy as np

class NumpyArray:
    def __init__(self,*z):
        self.z = np.array(z)
        self.x = np.arange(5,5*len(self.z)+1,5)
        self.y = np.random.randint(100,150,(len(self.z)))   
        
    
    def AddXY(self):
        print( self.x + self.y)

    def MultiplyXZ(self):
        print (self.x * self.z)

    def SubtractZY(self):
        print (self.z-self.y)

    def addXYZ(self):
        print (self.x + self.y + self.z)

    def getShapes(self):
        print (f'The shape of X is {np.shape(self.x)}. The shape of Y is {np.shape(self.y)}. The shape of Z is {np.shape(self.z)}')
     


In [ ]:

myArray = NumpyArray(1,3,5,6)
print(myArray.x)
print(myArray.z)
print(myArray.y)
myArray.getShapes()
myArray.AddXY()
myArray.MultiplyXZ()
myArray.SubtractZY()
myArray.addXYZ()


## 8.2 READING CSV (Follow)

**Learning Objectives:**

1. Understand how to read CSV into arrays.
2. Understand the data type of csv files.
3. Learn to manipulate CSV data.

In [ ]:
"""
Add comments for you own reference
"""

import numpy as np

data = np.loadtxt("test.csv",delimiter=",", dtype=int)
print(data)

In [ ]:
"""
Add comments for you own reference
"""

print("Type -",type(data))
print("Data Type -",data.dtype)
print("Size -",data.size)
print("ItemSize -",data.itemsize)
print("Dimensions -",data.ndim)
print("Shape -",data.shape)

**Evaluation:**

After running this program, think about and answer these questions:

1. What does astype() function do?
2. Search for alternate methods of loading.
3. What is the use of delimiter parameter?

## 8.2 READING CSV (Group)

Write a program that will do the following:

1. Read csv file 'test.csv'
2. Perform basic operations on 'test.csv'
    - Multiply each value by 2
    - Subtract each value by 50
3. Create an array X with same shape and random numbers
4. Add X to data
   

In [4]:
import numpy as np

class reading_CSV:
    def __init__(self,Filename):
        self.__filename = Filename
        self.__data = np.loadtxt(self.__filename,delimiter=",", dtype=int)
        self.__x =None
        
    def csvX2(self):
        self.__twos = np.full(self.__data.shape,2)
        print(self.__twos*self.__data)

    def csvMinus50(self):
        self.__fiftys = np.full(self.__data.shape,50)
        print(self.__data-self.__fiftys)

    def rndmX(self):
        self.__x = np.random.randint(1,99,self.__data.shape)
        print(self.__x)

    def AppendX(self):
        self.rndmX()
        print(self.__x.shape)
        newArr = np.concatenate((self.__data,self.__x),axis=0, out=None, dtype=int, casting="same_kind")
        print(newArr.shape)
        np.savetxt('appendCSV.csv',newArr,delimiter=",")

    def __str__(self):
        return f'{self.__data.shape}'

In [5]:
myCSV = reading_CSV('test.csv')
#myCSV.csvX2()
#myCSV.csvMinus50()

myCSV.AppendX()

(100, 10)
[[73 36 20 79  8 64 58 75 77  2]
 [83 26 73 12 55 68 36 23 75 45]
 [ 2 96 76 64 38 63 12 79 94  4]
 [38 89 18 72 96 46 35 45 63 71]
 [51 68 35 27 76 86 31 12  2 39]
 [96 37 32 25 43 23 72 66 34 77]
 [78 13 66 73 94 20 34 90 32 30]
 [39 36 55 87 86 90 39 74 10 48]
 [35 25  1 72 24  7 40  2 50  5]
 [38  1 67 31 50 94 81 82 13 63]
 [91 83 31 53 35  2 16 95 90  7]
 [71 40 82 41 23 37 94  1 81 45]
 [17 51 55 51 68 23 34 84 44 78]
 [82 63 72  4 55 73 14  6 19 59]
 [12 16 41 49 46 25 83 90 40 39]
 [ 1 26 76 71 70 62 69 12  3 38]
 [47 18 54 41 15 85 85 16 39 27]
 [ 8 63 67 28 65 64 94 27 34 12]
 [77 97 35 39 72 97 61 11 63  1]
 [ 6 47 77 75 64 27 26 28  5 16]
 [46 85 17 16 81 25 43 59 69 51]
 [76 19 52 55 25 92 64 29 35 63]
 [91 40 42 54 24 58 18 95 37 64]
 [29  5 35 45 59 21 81 20  1 77]
 [92 52 54 67 53 53 78 27 78 30]
 [77  2 16 22 86 68 76 54 77  7]
 [17 60 37  7 92 71 97 97 90 28]
 [45 75 81 27 58 57  5 54 69 85]
 [91 85 67  7 26 15 43 56 33 90]
 [63  6 25 19 84 25 12 22 80 39]


## 8.3 STATISTICS (Follow)

**Learning Objectives:**

1. Learn to perform statistical functions on Arrays.
2. Understand how arrays provide statistical analysis.
3. Understand how to perform statistical analysis of different dimensions of an array.

In [ ]:
"""
Add comments for you own reference
"""

import numpy as np

data = np.loadtxt("test.csv",delimiter=",", dtype=int)

print("Mean -")
print(data.mean())
print("Median -")
print(np.median(data))
print("Sum -")
print(np.sum(data[0]))
print("Standard Deviation -")
print(np.std(data))
print("Variation -")
print(np.var(data))

In [ ]:
#https://railsware.com/blog/python-for-machine-learning-pandas-axis-explained/#:~:text=%E2%80%9Caxis%200%E2%80%9D%20represents%20rows%20and,it%20goes%20along%20rows%20direction.
"""
Add comments for you own reference
"""

print("Mean by Rows-")
print(data.mean(axis=0))
print("Mean by Column-")
print(data.mean(axis=1))

**Evaluation:**

After running this program, think about and answer these questions:

1. What other functions are readily available?
2. What does axis parameter do?
3. How will different functions react to changes in dimensions of the array?

## 8.3 STATISTICS (Group)

Write a program that will do the following:

1. Get a number n from User (10-30)
2. Print the statistic information for every nth row of the 'test.csv'
    - Mean
    - Median
    - Sum
    - SD
    - Variation


In [33]:
import numpy as np

class reading_CSV:
    def __init__(self,Filename):
        self.__filename = Filename
        self.__data = np.loadtxt(self.__filename,delimiter=",", dtype=int)
        self.__x =None
    
    def PullNthRow(self):
        N = input('Please enter a number between 1 and 30')
        while (int(N) < self.__data.size):
            print("Mean -")
            print(self.__data.mean())
            print("Median -")
            print(np.median(self.__data))
            print("Sum -")
            print(np.sum(self.__data[0]))
            print("Standard Deviation -")
            print(np.std(self.__data))
            print("Variation -")
            print(np.var(self.__data))
            N += N
    
    def __str__(self):
        return f'{self.__data.shape}'


In [35]:
myCSV = reading_CSV('test.csv')
myCSV.PullNthRow()

Mean -
49.305
Median -
51.0
Sum -
490
Standard Deviation -
28.376398203436604
Variation -
805.2199750000001


## 8.4 INDEXING (Follow)

**Learning Objectives:**

1. Understand how Indexing in arrays works.
2. Understand how slicing in arrays works.
3. Learn to extract relevant information from numpy array.

In [ ]:
"""
Add comments for you own reference
"""

import numpy as np

data = np.loadtxt("test.csv",delimiter=",", dtype=int)

print('Item at index (20,4):\n',data[20,4],'\n')

In [ ]:
"""
Add comments for you own reference
"""

print('Slice of rows 20 - 25:\n',data[20:25],'\n')
print('Specific rows (multiples of 10):\n',data[[i for i in range(0,100,10)]],'\n')

In [ ]:
"""
Add comments for you own reference
"""

print('Slice of columns 5 - 8:\n',data[:,5:8],'\n')
print('Specific columns (multiples of 2):\n',data[:,[i for i in range(0,10,2)]],'\n')

In [ ]:
"""
Add comments for you own reference
"""

print('Slice of rows 20-25 & columns 5 - 8:\n',data[20:25,5:8],'\n')

**Evaluation:**

After running this program, think about and answer these questions:

1. What is the use case for slicing and indexing?
2. Try to manipulate the array by slicing differently.

## 8.4 INDEXING (Group)

Write a program that will do the following:

1. Use 'test.csv' 
2. Get a row and column number from the user and display the value at the index
3. Get a range of rows and columns from the user and display all rows in column range and all columns in row range and also all data in row and column range
4. Add rows 10-15 with rows 50-55 and display output

## 8.5 COPY VS VIEW (Follow)

**Learning Objectives:**

1. Understand the difference between a copy and a view.
2. Understand how the original array is affected when deling with views.
3. Understand how the original array is affected when deling with copies.
4. Learn to manipulate data using copies and views

In [ ]:
"""
Add comments for you own reference
"""

arr = np.array([1,2,3,4,5])
print("Original Before -")
print(arr)
x = arr.view()
x[0] = 9
print("Original for view -")
print(arr)
print("View -")
print(x)
y = arr.copy()
y[1] = 8
print("Original for copy -")
print(arr)
print("Copy -")
print(y)

In [ ]:
"""
Add comments for you own reference
"""

data = np.loadtxt("test.csv",delimiter=",", dtype=int)
data = data[5:10]

print("Original Before -")
print(data)
x = data.view()
x[0] = 9
print("Original for view -")
print(data)
print("View -")
print(x)
y = data.copy()
y[1] = 8
print("Original for copy -")
print(data)
print("Copy -")
print(y)

**Evaluation:**

After running this program, think about and answer these questions:

1. What does the copy() function do?
2. What does the view() function do?
3. How is the original array affected by manipulating views / copies?
4. What is the best use case for views?
5. What is the best use case for copies?

## 8.5 COPY VS VIEW (Group)

Write a program that will do the following:

1. Read 'test.csv' 
2. Make a copy and a view of the data
3. Convert even rows of view to all 5
4. Convert odd rows of copy to all 10
5. Add Copy to view
6. Display all three Arrays

## 8.6 MODIFICATION (Follow)

**Learning Objectives:**

1. Understand how to modify an array.
2. Learn modification functions.
3. Understand the use of array modification

In [ ]:
"""
Add comments for you own reference
"""

import numpy as np
arr = np.array([1,2,3,4,5,6])
arr.resize(2,3)
print(arr,"\n")
x = arr.reshape(3,2)
print(x,"\n")
y = x.flatten()
z = x.ravel()
y[0] = 99
z[0] = 88
print(x,"\n")
print(y,"\n")
print(z,"\n")
print(x.transpose(),"\n")

In [ ]:
"""
Add comments for you own reference
"""

data = np.loadtxt("test.csv",delimiter=",", dtype=str).astype(int)
data = data[25:30]

data.resize(25,2)
print(data,"\n")
x = data.reshape(10,5)
print(x,"\n")
y = x.flatten()
z = x.ravel()
y[0] = 99
z[0] = 88
print(x,"\n")
print(y,"\n")
print(z,"\n")
print(x.transpose(),"\n")

**Evaluation:**

After running this program, think about and answer these questions:

1. What is the difference between resize and reshape?
2. What is the difference between ravel and flatten?
3. What does transpose() function do?
4. How are these functions helpful in data analysis or statistics?

## 8.6 MODIFICATION (Group)

Write a program that will do the following:

1. Read 'test.csv' 
2. Slice a 5:8 grid from the array (X)
3. Make a copy and transpose (X)
4. Reshape both arrays to (4,10)
5. Multiply the arrays and display the Output
6. Try to display each step